"""Validation, catalog generation, and SQLite FTS5 indexing."""

from __future__ import annotations

import sqlite3
from pathlib import Path

from .model import Document
from .workspace import Workspace, atomic_write, validate_workspace


def _catalog(workspace: Workspace, documents: list[Document]) -> bytes:
    lines = [
        "# Knowledge OS catalog",
        "",
        "Generated by `kos index`; Markdown records remain authoritative.",
        "",
        "| ID | Title | Type | Status | Scope | Path |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for document in documents:
        metadata = document.metadata
        values = [
            metadata["id"],
            metadata["title"],
            metadata["type"],
            metadata["status"],
            metadata["scope"],
            workspace.relative(document.path),
        ]
        lines.append(
            "| "
            + " | ".join(str(value).replace("\n", " ").replace("|", "\\|") for value in values)
            + " |"
        )
    lines.extend(["", f"Total records: {len(documents)}", ""])
    return "\n".join(lines).encode("utf-8")


def _build_sqlite(path: Path, workspace: Workspace, documents: list[Document]) -> None:
    connection = sqlite3.connect(path)
    try:
        connection.executescript(
            """
            PRAGMA user_version = 1;
            CREATE VIRTUAL TABLE documents_fts USING fts5(
                id, title, type, status, scope, path, tags, body
            );
            """
        )
        for document in documents:
            metadata = document.metadata
            values = (
                metadata["id"],
                metadata["title"],
                metadata["type"],
                metadata["status"],
                metadata["scope"],
                workspace.relative(document.path),
                " ".join(metadata.get("tags", [])),
                document.body,
            )
            connection.execute("INSERT INTO documents_fts VALUES (?, ?, ?, ?, ?, ?, ?, ?)", values)
        connection.commit()
    finally:
        connection.close()


def rebuild_indexes(workspace: Workspace) -> int:
    documents, issues = validate_workspace(workspace)
    if issues:
        details = "\n".join(f"{issue.path}: {issue.message}" for issue in issues)
        raise ValueError(f"cannot index invalid corpus:\n{details}")
    indexes = workspace.root / "indexes"
    indexes.mkdir(parents=True, exist_ok=True)
    sqlite_path = indexes / "catalog.sqlite3"
    temp_sqlite = indexes / ".catalog.sqlite3.tmp"
    temp_sqlite.unlink(missing_ok=True)
    try:
        _build_sqlite(temp_sqlite, workspace, documents)
        atomic_write(indexes / "catalog.md", _catalog(workspace, documents))
        temp_sqlite.replace(sqlite_path)
    finally:
        temp_sqlite.unlink(missing_ok=True)
    return len(documents)


def search_index(workspace: Workspace, query: str, limit: int) -> list[dict[str, str]]:
    database = workspace.root / "indexes" / "catalog.sqlite3"
    if not database.is_file():
        raise ValueError("search index is absent; run 'kos index' first")
    if not query.strip():
        raise ValueError("search query must not be empty")
    escaped = query.replace('"', '""')
    connection = sqlite3.connect(database)
    connection.row_factory = sqlite3.Row
    try:
        rows = connection.execute(
            """
            SELECT id, title, type, status, scope, path,
                   snippet(documents_fts, 7, '[', ']', '...', 18) AS snippet
            FROM documents_fts
            WHERE documents_fts MATCH ?
            ORDER BY bm25(documents_fts), id
            LIMIT ?
            """,
            (f'"{escaped}"', limit),
        ).fetchall()
    except sqlite3.OperationalError as exc:
        raise ValueError(f"search query could not be parsed: {exc}") from exc
    finally:
        connection.close()
    results = [dict(row) for row in rows]
    for result in results:
        result["snippet"] = " ".join(result["snippet"].split())
    return results
