"""Validation, catalog generation, and SQLite FTS5 indexing."""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any, Iterable

from .model import Document
from .workspace import Workspace, atomic_write, validate_workspace, workspace_mutation_lock


def _record_kind(metadata: dict[str, Any]) -> str:
    if metadata["type"] in {"knowledge", "project"}:
        return metadata.get("record_kind", "ordinary")
    return ""


def _catalog(workspace: Workspace, documents: list[Document]) -> bytes:
    lines = [
        "# Knowledge OS catalog",
        "",
        "Generated by `kos index`; Markdown records remain authoritative.",
        "",
        "| ID | Title | Type | Record kind | Status | Scope | Path |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for document in documents:
        metadata = document.metadata
        values = [
            metadata["id"],
            metadata["title"],
            metadata["type"],
            _record_kind(metadata),
            metadata["status"],
            metadata["scope"],
            workspace.relative(document.path),
        ]
        lines.append(
            "| "
            + " | ".join(str(value).replace("\n", " ").replace("|", "\\|") for value in values)
            + " |"
        )
    lines.extend(["", f"Total records: {len(documents)}", ""])
    return "\n".join(lines).encode("utf-8")


def _build_sqlite(path: Path, workspace: Workspace, documents: list[Document]) -> None:
    connection = sqlite3.connect(path)
    try:
        connection.executescript(
            """
            PRAGMA user_version = 1;
            CREATE VIRTUAL TABLE documents_fts USING fts5(
                id, title, type, record_kind, status, scope, path, tags, body
            );
            """
        )
        for document in documents:
            metadata = document.metadata
            values = (
                metadata["id"],
                metadata["title"],
                metadata["type"],
                _record_kind(metadata),
                metadata["status"],
                metadata["scope"],
                workspace.relative(document.path),
                " ".join(metadata.get("tags", [])),
                document.body,
            )
            connection.execute("INSERT INTO documents_fts VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", values)
        connection.commit()
    finally:
        connection.close()


def _rebuild_indexes_locked(workspace: Workspace) -> int:
    documents, issues = validate_workspace(workspace)
    if issues:
        details = "\n".join(f"{issue.path}: {issue.message}" for issue in issues)
        raise ValueError(f"cannot index invalid corpus:\n{details}")
    indexes = workspace.root / "indexes"
    workspace.assert_safe_path(indexes)
    indexes.mkdir(parents=True, exist_ok=True)
    sqlite_path = indexes / "catalog.sqlite3"
    catalog_path = indexes / "catalog.md"
    temp_sqlite = indexes / ".catalog.sqlite3.tmp"
    workspace.assert_safe_path(catalog_path)
    workspace.assert_safe_path(sqlite_path)
    workspace.assert_safe_path(temp_sqlite)
    temp_sqlite.unlink(missing_ok=True)
    try:
        _build_sqlite(temp_sqlite, workspace, documents)
        atomic_write(catalog_path, _catalog(workspace, documents))
        temp_sqlite.replace(sqlite_path)
    finally:
        temp_sqlite.unlink(missing_ok=True)
    return len(documents)


def rebuild_indexes(workspace: Workspace) -> int:
    """Validate and replace both disposable indexes under the workspace lock."""

    with workspace_mutation_lock(workspace):
        return _rebuild_indexes_locked(workspace)


def search_index(workspace: Workspace, query: str, limit: int) -> list[dict[str, str]]:
    workspace.assert_safe_path(workspace.root / "indexes")
    database = workspace.root / "indexes" / "catalog.sqlite3"
    workspace.assert_safe_path(database)
    if not database.is_file():
        raise ValueError("search index is absent; run 'kos index' first")
    if not query.strip():
        raise ValueError("search query must not be empty")
    escaped = query.replace('"', '""')
    connection = sqlite3.connect(database)
    connection.row_factory = sqlite3.Row
    try:
        rows = connection.execute(
            """
            SELECT id, title, type, record_kind, status, scope, path,
                   snippet(documents_fts, 8, '[', ']', '...', 18) AS snippet
            FROM documents_fts
            WHERE documents_fts MATCH ?
            ORDER BY bm25(documents_fts), id
            LIMIT ?
            """,
            (f'"{escaped}"', limit),
        ).fetchall()
    except sqlite3.OperationalError as exc:
        raise ValueError(f"search query could not be parsed: {exc}") from exc
    finally:
        connection.close()
    results = [dict(row) for row in rows]
    for result in results:
        result["snippet"] = " ".join(result["snippet"].split())
    return results


def _fts_query(terms: Iterable[str]) -> str:
    quoted = [f'"{term.replace(chr(34), chr(34) * 2)}"' for term in terms if term.strip()]
    return " OR ".join(quoted)


def search_index_terms(
    workspace: Workspace,
    terms: Iterable[str],
    scopes: Iterable[str],
    statuses: Iterable[str],
    types: Iterable[str] | None = None,
) -> list[dict[str, Any]]:
    """Return eligible FTS matches ranked by distinct matched request terms.

    This is deliberately read-only and does not attempt to refresh the cache. The
    per-term queries preserve SQLite tokenizer semantics while keeping excluded
    scopes and statuses from affecting result order.
    """

    workspace.assert_safe_path(workspace.root / "indexes")
    database = workspace.root / "indexes" / "catalog.sqlite3"
    workspace.assert_safe_path(database)
    if not database.is_file():
        raise ValueError("search index is absent; run 'kos index' first")
    distinct_terms = tuple(dict.fromkeys(term for term in terms if term.strip()))
    if not distinct_terms:
        raise ValueError("context request must contain at least one searchable term")
    allowed_scopes = tuple(dict.fromkeys(scope for scope in scopes if scope.strip()))
    if not allowed_scopes:
        raise ValueError("context search requires at least one scope")
    allowed_statuses = tuple(dict.fromkeys(status for status in statuses if status.strip()))
    if not allowed_statuses:
        raise ValueError("context search requires at least one status")
    allowed_types = tuple(dict.fromkeys(record_type for record_type in (types or ()) if record_type.strip()))
    scope_placeholders = ", ".join("?" for _ in allowed_scopes)
    status_placeholders = ", ".join("?" for _ in allowed_statuses)
    type_clause = ""
    if types is not None:
        if not allowed_types:
            raise ValueError("context search requires at least one type")
        type_clause = f" AND type IN ({', '.join('?' for _ in allowed_types)})"
    connection = sqlite3.connect(f"file:{database.as_posix()}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    try:
        matched_ids: set[str] = set()
        matched_terms: dict[str, list[str]] = {}
        for term in distinct_terms:
            rows = connection.execute(
                f"""
                SELECT id
                FROM documents_fts
                WHERE documents_fts MATCH ?
                  AND scope IN ({scope_placeholders})
                  AND status IN ({status_placeholders})
                  {type_clause}
                ORDER BY id
                """,
                (_fts_query((term,)), *allowed_scopes, *allowed_statuses, *allowed_types),
            ).fetchall()
            for row in rows:
                record_id = row["id"]
                matched_ids.add(record_id)
                matched_terms.setdefault(record_id, []).append(term)
    except sqlite3.OperationalError as exc:
        raise ValueError(f"context search query could not be parsed: {exc}") from exc
    finally:
        connection.close()
    ordered = sorted(matched_ids, key=lambda record_id: (-len(matched_terms[record_id]), record_id))
    return [
        {"id": record_id, "matched_terms": matched_terms[record_id], "fts_rank": rank}
        for rank, record_id in enumerate(ordered)
    ]


def validate_index(workspace: Workspace, documents: list[Document]) -> None:
    """Ensure the read-only cache describes the current valid Markdown corpus."""

    workspace.assert_safe_path(workspace.root / "indexes")
    database = workspace.root / "indexes" / "catalog.sqlite3"
    workspace.assert_safe_path(database)
    if not database.is_file():
        raise ValueError("search index is absent; run 'kos index' first")
    expected = sorted(
        (
            document.metadata["id"],
            document.metadata["title"],
            document.metadata["type"],
            _record_kind(document.metadata),
            document.metadata["status"],
            document.metadata["scope"],
            workspace.relative(document.path),
            " ".join(document.metadata.get("tags", [])),
            document.body,
        )
        for document in documents
    )
    try:
        connection = sqlite3.connect(f"file:{database.as_posix()}?mode=ro", uri=True)
        connection.row_factory = sqlite3.Row
        try:
            actual = [
                tuple(row)
                for row in connection.execute(
                    "SELECT id, title, type, record_kind, status, scope, path, tags, body FROM documents_fts ORDER BY id"
                )
            ]
        finally:
            connection.close()
    except (sqlite3.DatabaseError, OSError) as exc:
        raise ValueError(f"search index could not be read: {exc}") from exc
    if actual != expected:
        raise ValueError("search index is stale; run 'kos index' first")
